import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";

import Header from "@/components/Header/Header";

const roboto = Roboto({ weight: ['400', '500', '700'], style: ['normal'], subsets: ['latin']});

export const metadata: Metadata = {
  title: "MCS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className} style={{position: 'relative'}}>
        <Header/>
        {children}</body>
    </html>
  );
}
