import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import ScrollUpButton from "@/components/ui/ScrollUpButton/ScrollUpButton";

const roboto = Roboto({ weight: ['400', '500', '700'], style: ['normal'], subsets: ['latin']});

export const metadata: Metadata = {
  title: "MCS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        {children}
        <Footer/>
        <ScrollUpButton/>
        </body>
    </html>
  );
}
